# The version of the configuration file format
version: 1
# Your module version - must be changed to release a new version
module_version: 0.1.0

# Any default settings that should be used for all test cases
test_defaults:
  before_init: ["tofu fmt -recursive -check"]
  project_root: examples/simple-stack

# Place tests here
tests:
  - name: simple-stack with tofu 1.6.2
    terraform_version: 1.6.2
  - name: simple-stack with tofu 1.9.0
    terraform_version: 1.9.0