# The version of the configuration file format
version: 1
# Your module version - must be changed to release a new version
module_version: 0.1.0

# Any default settings that should be used for all test cases
test_defaults:
  before_init: ["tofu fmt -check"]

# Place tests here
# verify that context was attached to stack